"""Embed the pinned ENS normalization tables for every wallet build target."""

import base64
import hashlib
from pathlib import Path
import textwrap

root = Path(__file__).resolve().parents[1]
source = root / "Sources/ENSNormalize"
lines = [
    "// Generated by scripts/embed-ens-normalization-data.py from ENSNormalize.swift v1.0.1.",
    "// Upstream MIT license: Sources/ENSNormalize/LICENSE.",
    "import Foundation",
    "",
    "enum NormalizationData {",
]
for name in ("nf", "spec"):
    data = (source / "data" / f"{name}.bin").read_bytes()
    lines.extend(
        [
            f"  // SHA-256: {hashlib.sha256(data).hexdigest()}",
            f'  static let {name} = decode(',
            '    """',
            *[f"    {line}" for line in textwrap.wrap(base64.b64encode(data).decode(), 96)],
            '    """',
            '  )',
            "",
        ]
    )
lines.extend(
    [
        "  private static func decode(_ encoded: String) -> Data {",
        "    guard let data = Data(base64Encoded: encoded, options: .ignoreUnknownCharacters) else {",
        '      fatalError("Corrupt embedded ENS normalization table")',
        "    }",
        "    return data",
        "  }",
        "}",
        "",
    ]
)
(source / "NormalizationData.swift").write_text("\n".join(lines))
